// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers 
(operator_id, external_id, plan_name, name, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, operator_id, external_id, name, email, period_start, created_at, plan_name
`

type CreateCustomerParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	ExternalID pgtype.UUID `json:"external_id"`
	PlanName   string      `json:"plan_name"`
	Name       string      `json:"name"`
	Email      string      `json:"email"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.OperatorID,
		arg.ExternalID,
		arg.PlanName,
		arg.Name,
		arg.Email,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ExternalID,
		&i.Name,
		&i.Email,
		&i.PeriodStart,
		&i.CreatedAt,
		&i.PlanName,
	)
	return i, err
}

const getCustomerByEmail = `-- name: GetCustomerByEmail :one
SELECT id, operator_id, external_id, name, email, period_start, created_at, plan_name FROM customers WHERE operator_id = $1 AND email = $2
`

type GetCustomerByEmailParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	Email      string      `json:"email"`
}

func (q *Queries) GetCustomerByEmail(ctx context.Context, arg GetCustomerByEmailParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByEmail, arg.OperatorID, arg.Email)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ExternalID,
		&i.Name,
		&i.Email,
		&i.PeriodStart,
		&i.CreatedAt,
		&i.PlanName,
	)
	return i, err
}

const getCustomerByExternalID = `-- name: GetCustomerByExternalID :one
SELECT id, operator_id, external_id, name, email, period_start, created_at, plan_name FROM customers WHERE operator_id = $1 AND external_id = $2
`

type GetCustomerByExternalIDParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	ExternalID pgtype.UUID `json:"external_id"`
}

func (q *Queries) GetCustomerByExternalID(ctx context.Context, arg GetCustomerByExternalIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByExternalID, arg.OperatorID, arg.ExternalID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ExternalID,
		&i.Name,
		&i.Email,
		&i.PeriodStart,
		&i.CreatedAt,
		&i.PlanName,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT id, operator_id, external_id, name, email, period_start, created_at, plan_name FROM customers WHERE id = $1
`

func (q *Queries) GetCustomerByID(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByID, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ExternalID,
		&i.Name,
		&i.Email,
		&i.PeriodStart,
		&i.CreatedAt,
		&i.PlanName,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, operator_id, external_id, name, email, period_start, created_at, plan_name FROM customers WHERE operator_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListCustomers(ctx context.Context, operatorID pgtype.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.ExternalID,
			&i.Name,
			&i.Email,
			&i.PeriodStart,
			&i.CreatedAt,
			&i.PlanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerPlan = `-- name: UpdateCustomerPlan :one
UPDATE customers SET plan_name = $1, updated_at = NOW() WHERE operator_id = $2 AND id = $3 RETURNING id, operator_id, external_id, name, email, period_start, created_at, plan_name
`

type UpdateCustomerPlanParams struct {
	PlanName   string      `json:"plan_name"`
	OperatorID pgtype.UUID `json:"operator_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCustomerPlan(ctx context.Context, arg UpdateCustomerPlanParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerPlan, arg.PlanName, arg.OperatorID, arg.ID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ExternalID,
		&i.Name,
		&i.Email,
		&i.PeriodStart,
		&i.CreatedAt,
		&i.PlanName,
	)
	return i, err
}
