// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUsageEvent = `-- name: CreateUsageEvent :one
INSERT INTO usage_events (customer_id, operator_id, event_name, quantity, idempotency_key)
VALUES ($1, $2, $3, $4, $5) RETURNING id, customer_id, operator_id, event_name, quantity, idempotency_key, created_at
`

type CreateUsageEventParams struct {
	CustomerID     pgtype.UUID `json:"customer_id"`
	OperatorID     pgtype.UUID `json:"operator_id"`
	EventName      string      `json:"event_name"`
	Quantity       int64       `json:"quantity"`
	IdempotencyKey string      `json:"idempotency_key"`
}

func (q *Queries) CreateUsageEvent(ctx context.Context, arg CreateUsageEventParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, createUsageEvent,
		arg.CustomerID,
		arg.OperatorID,
		arg.EventName,
		arg.Quantity,
		arg.IdempotencyKey,
	)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OperatorID,
		&i.EventName,
		&i.Quantity,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageEventByCustomerID = `-- name: GetUsageEventByCustomerID :one
SELECT id, customer_id, operator_id, event_name, quantity, idempotency_key, created_at FROM usage_events WHERE customer_id = $1
`

func (q *Queries) GetUsageEventByCustomerID(ctx context.Context, customerID pgtype.UUID) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEventByCustomerID, customerID)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OperatorID,
		&i.EventName,
		&i.Quantity,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageEventByCustomerIDAndEventName = `-- name: GetUsageEventByCustomerIDAndEventName :one
SELECT id, customer_id, operator_id, event_name, quantity, idempotency_key, created_at FROM usage_events WHERE customer_id = $1 AND event_name = $2
`

type GetUsageEventByCustomerIDAndEventNameParams struct {
	CustomerID pgtype.UUID `json:"customer_id"`
	EventName  string      `json:"event_name"`
}

func (q *Queries) GetUsageEventByCustomerIDAndEventName(ctx context.Context, arg GetUsageEventByCustomerIDAndEventNameParams) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEventByCustomerIDAndEventName, arg.CustomerID, arg.EventName)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OperatorID,
		&i.EventName,
		&i.Quantity,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageEventByID = `-- name: GetUsageEventByID :one
SELECT id, customer_id, operator_id, event_name, quantity, idempotency_key, created_at FROM usage_events WHERE id = $1
`

func (q *Queries) GetUsageEventByID(ctx context.Context, id pgtype.UUID) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEventByID, id)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OperatorID,
		&i.EventName,
		&i.Quantity,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageEventByIdempotencyKey = `-- name: GetUsageEventByIdempotencyKey :one
SELECT id, customer_id, operator_id, event_name, quantity, idempotency_key, created_at FROM usage_events WHERE idempotency_key = $1
`

func (q *Queries) GetUsageEventByIdempotencyKey(ctx context.Context, idempotencyKey string) (UsageEvent, error) {
	row := q.db.QueryRow(ctx, getUsageEventByIdempotencyKey, idempotencyKey)
	var i UsageEvent
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.OperatorID,
		&i.EventName,
		&i.Quantity,
		&i.IdempotencyKey,
		&i.CreatedAt,
	)
	return i, err
}

const listUsageEventsByCustomerID = `-- name: ListUsageEventsByCustomerID :many
SELECT id, customer_id, operator_id, event_name, quantity, idempotency_key, created_at FROM usage_events WHERE customer_id = $1
`

func (q *Queries) ListUsageEventsByCustomerID(ctx context.Context, customerID pgtype.UUID) ([]UsageEvent, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByCustomerID, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageEvent
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.OperatorID,
			&i.EventName,
			&i.Quantity,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageEventsByEventName = `-- name: ListUsageEventsByEventName :many
SELECT id, customer_id, operator_id, event_name, quantity, idempotency_key, created_at FROM usage_events WHERE event_name = $1
`

func (q *Queries) ListUsageEventsByEventName(ctx context.Context, eventName string) ([]UsageEvent, error) {
	rows, err := q.db.Query(ctx, listUsageEventsByEventName, eventName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UsageEvent
	for rows.Next() {
		var i UsageEvent
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.OperatorID,
			&i.EventName,
			&i.Quantity,
			&i.IdempotencyKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
