// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNewInvoice = `-- name: CreateNewInvoice :one
INSERT INTO invoices (
    operator_id,
    customer_id,
    amount_cents,
    status,
    period_start,
    period_end,
    line_items
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, operator_id, customer_id, amount_cents, status, period_start, period_end, line_items, created_at
`

type CreateNewInvoiceParams struct {
	OperatorID  pgtype.UUID        `json:"operator_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	AmountCents int64              `json:"amount_cents"`
	Status      InvoiceStatus      `json:"status"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	LineItems   []byte             `json:"line_items"`
}

func (q *Queries) CreateNewInvoice(ctx context.Context, arg CreateNewInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createNewInvoice,
		arg.OperatorID,
		arg.CustomerID,
		arg.AmountCents,
		arg.Status,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.LineItems,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.CustomerID,
		&i.AmountCents,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.LineItems,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomersDueForBillingWithoutInvoice = `-- name: GetCustomersDueForBillingWithoutInvoice :many
SELECT 
c.id AS customer_id,
c.operator_id,
c.name AS customer_name,
c.period_start,
p.name AS plan_name,
p.pricing_model AS plan_pricing_model,
p.tiers AS plan_tiers,
p.unit_price_cent AS plan_unit_price,
p.billing_period AS plan_billing_period,
ua.total_units,
ua.event_name
FROM customers c
JOIN plans p ON p.name = c.plan_name
LEFT JOIN usage_aggregates ua ON ua.customer_id = c.id AND ua.period_start = c.period_start
WHERE (
    (p.billing_period = 'monthly' AND c.period_start + INTERVAL '1 month' <= NOW()) 
    OR
    (p.billing_period = 'yearly' AND c.period_start + INTERVAL '1 year' <= NOW())
)
AND NOT EXISTS (
    SELECT 1
    FROM invoices i
    WHERE i.customer_id = c.id
    AND i.period_start = c.period_start
    AND i.status != 'void'
)
ORDER BY c.id
`

type GetCustomersDueForBillingWithoutInvoiceRow struct {
	CustomerID        pgtype.UUID        `json:"customer_id"`
	OperatorID        pgtype.UUID        `json:"operator_id"`
	CustomerName      string             `json:"customer_name"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PlanName          string             `json:"plan_name"`
	PlanPricingModel  PricingType        `json:"plan_pricing_model"`
	PlanTiers         []byte             `json:"plan_tiers"`
	PlanUnitPrice     pgtype.Int8        `json:"plan_unit_price"`
	PlanBillingPeriod BillingPeriodType  `json:"plan_billing_period"`
	TotalUnits        pgtype.Int8        `json:"total_units"`
	EventName         pgtype.Text        `json:"event_name"`
}

func (q *Queries) GetCustomersDueForBillingWithoutInvoice(ctx context.Context) ([]GetCustomersDueForBillingWithoutInvoiceRow, error) {
	rows, err := q.db.Query(ctx, getCustomersDueForBillingWithoutInvoice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersDueForBillingWithoutInvoiceRow
	for rows.Next() {
		var i GetCustomersDueForBillingWithoutInvoiceRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.OperatorID,
			&i.CustomerName,
			&i.PeriodStart,
			&i.PlanName,
			&i.PlanPricingModel,
			&i.PlanTiers,
			&i.PlanUnitPrice,
			&i.PlanBillingPeriod,
			&i.TotalUnits,
			&i.EventName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInvoiceByID = `-- name: GetInvoiceByID :one
SELECT id, operator_id, customer_id, amount_cents, status, period_start, period_end, line_items, created_at FROM invoices 
WHERE id = $1
`

func (q *Queries) GetInvoiceByID(ctx context.Context, id pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoiceByID, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.CustomerID,
		&i.AmountCents,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.LineItems,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoicesByCustomer = `-- name: ListInvoicesByCustomer :many
SELECT id, operator_id, customer_id, amount_cents, status, period_start, period_end, line_items, created_at FROM invoices
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByCustomer(ctx context.Context, customerID pgtype.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.CustomerID,
			&i.AmountCents,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.LineItems,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByOperator = `-- name: ListInvoicesByOperator :many
SELECT id, operator_id, customer_id, amount_cents, status, period_start, period_end, line_items, created_at FROM invoices
WHERE operator_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListInvoicesByOperator(ctx context.Context, operatorID pgtype.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByOperator, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.CustomerID,
			&i.AmountCents,
			&i.Status,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.LineItems,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerPeriodStart = `-- name: UpdateCustomerPeriodStart :exec
UPDATE customers
SET period_start = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateCustomerPeriodStartParams struct {
	ID          pgtype.UUID        `json:"id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
}

func (q *Queries) UpdateCustomerPeriodStart(ctx context.Context, arg UpdateCustomerPeriodStartParams) error {
	_, err := q.db.Exec(ctx, updateCustomerPeriodStart, arg.ID, arg.PeriodStart)
	return err
}

const updateInvoiceStatus = `-- name: UpdateInvoiceStatus :one
UPDATE invoices
SET status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, operator_id, customer_id, amount_cents, status, period_start, period_end, line_items, created_at
`

type UpdateInvoiceStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status InvoiceStatus `json:"status"`
}

func (q *Queries) UpdateInvoiceStatus(ctx context.Context, arg UpdateInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.CustomerID,
		&i.AmountCents,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.LineItems,
		&i.CreatedAt,
	)
	return i, err
}
