// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invoice.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCustomersDueForBillingWithoutInvoice = `-- name: GetCustomersDueForBillingWithoutInvoice :many
SELECT 
c.id AS customer_id,
c.operator_id,
c.name AS customer_name,
c.period_start,
p.name AS plan_name,
p.pricing_model AS plan_pricing_model,
p.tiers AS plan_tiers,
p.unit_price_cent AS plan_unit_price,
p.billing_period AS plan_billing_period,
ua.total_units,
ua.event_name
FROM customers c
JOIN plans p ON p.name = c.plan_name
LEFT JOIN usage_aggregates ua ON ua.customer_id = c.id AND ua.period_start = c.period_start
WHERE (
    (p.billing_period = 'monthly' AND c.period_start + INTERVAL '1 month' <= NOW()) 
    OR
    (p.billing_period = 'yearly' AND c.period_start + INTERVAL '1 year' <= NOW())
)
AND NOT EXISTS (
    SELECT 1
    FROM invoices i
    WHERE i.customer_id = c.id
    AND i.period_start = c.period_start
    AND i.status != 'void'
)
ORDER BY c.id
`

type GetCustomersDueForBillingWithoutInvoiceRow struct {
	CustomerID        pgtype.UUID        `json:"customer_id"`
	OperatorID        pgtype.UUID        `json:"operator_id"`
	CustomerName      string             `json:"customer_name"`
	PeriodStart       pgtype.Timestamptz `json:"period_start"`
	PlanName          string             `json:"plan_name"`
	PlanPricingModel  PricingType        `json:"plan_pricing_model"`
	PlanTiers         []byte             `json:"plan_tiers"`
	PlanUnitPrice     pgtype.Int8        `json:"plan_unit_price"`
	PlanBillingPeriod BillingPeriodType  `json:"plan_billing_period"`
	TotalUnits        pgtype.Int8        `json:"total_units"`
	EventName         pgtype.Text        `json:"event_name"`
}

func (q *Queries) GetCustomersDueForBillingWithoutInvoice(ctx context.Context) ([]GetCustomersDueForBillingWithoutInvoiceRow, error) {
	rows, err := q.db.Query(ctx, getCustomersDueForBillingWithoutInvoice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersDueForBillingWithoutInvoiceRow
	for rows.Next() {
		var i GetCustomersDueForBillingWithoutInvoiceRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.OperatorID,
			&i.CustomerName,
			&i.PeriodStart,
			&i.PlanName,
			&i.PlanPricingModel,
			&i.PlanTiers,
			&i.PlanUnitPrice,
			&i.PlanBillingPeriod,
			&i.TotalUnits,
			&i.EventName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
