// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingPeriodType string

const (
	BillingPeriodTypeMonthly BillingPeriodType = "monthly"
	BillingPeriodTypeYearly  BillingPeriodType = "yearly"
)

func (e *BillingPeriodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingPeriodType(s)
	case string:
		*e = BillingPeriodType(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingPeriodType: %T", src)
	}
	return nil
}

type NullBillingPeriodType struct {
	BillingPeriodType BillingPeriodType `json:"billing_period_type"`
	Valid             bool              `json:"valid"` // Valid is true if BillingPeriodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingPeriodType) Scan(value interface{}) error {
	if value == nil {
		ns.BillingPeriodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingPeriodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingPeriodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingPeriodType), nil
}

type OperatingStatus string

const (
	OperatingStatusActive      OperatingStatus = "active"
	OperatingStatusInactive    OperatingStatus = "inactive"
	OperatingStatusMaintenance OperatingStatus = "maintenance"
	OperatingStatusDeprecated  OperatingStatus = "deprecated"
)

func (e *OperatingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OperatingStatus(s)
	case string:
		*e = OperatingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OperatingStatus: %T", src)
	}
	return nil
}

type NullOperatingStatus struct {
	OperatingStatus OperatingStatus `json:"operating_status"`
	Valid           bool            `json:"valid"` // Valid is true if OperatingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperatingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OperatingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OperatingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperatingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OperatingStatus), nil
}

type PricingType string

const (
	PricingTypeFlat    PricingType = "flat"
	PricingTypeTiered  PricingType = "tiered"
	PricingTypePerUnit PricingType = "per_unit"
)

func (e *PricingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingType(s)
	case string:
		*e = PricingType(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingType: %T", src)
	}
	return nil
}

type NullPricingType struct {
	PricingType PricingType `json:"pricing_type"`
	Valid       bool        `json:"valid"` // Valid is true if PricingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingType) Scan(value interface{}) error {
	if value == nil {
		ns.PricingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingType), nil
}

type Customer struct {
	ID          pgtype.UUID        `json:"id"`
	OperatorID  pgtype.UUID        `json:"operator_id"`
	ExternalID  pgtype.UUID        `json:"external_id"`
	PlanID      pgtype.UUID        `json:"plan_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Operator struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	LogoUrl       pgtype.Text        `json:"logo_url"`
	ApiKeyHash    string             `json:"api_key_hash"`
	WebhookSecret string             `json:"webhook_secret"`
	SupportEmail  pgtype.Text        `json:"support_email"`
	WebsiteUrl    pgtype.Text        `json:"website_url"`
	Status        OperatingStatus    `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Plan struct {
	ID            pgtype.UUID        `json:"id"`
	OperatorID    pgtype.UUID        `json:"operator_id"`
	Name          string             `json:"name"`
	PricingModel  PricingType        `json:"pricing_model"`
	UnitPriceCent pgtype.Int8        `json:"unit_price_cent"`
	Tiers         []byte             `json:"tiers"`
	BillingPeriod BillingPeriodType  `json:"billing_period"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UsageEvent struct {
	ID             pgtype.UUID `json:"id"`
	CustomerID     pgtype.UUID `json:"customer_id"`
	OperatorID     pgtype.UUID `json:"operator_id"`
	EventName      string      `json:"event_name"`
	IdempotencyKey string      `json:"idempotency_key"`
}
