// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type BillingPeriodType string

const (
	BillingPeriodTypeMonthly BillingPeriodType = "monthly"
	BillingPeriodTypeYearly  BillingPeriodType = "yearly"
)

func (e *BillingPeriodType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingPeriodType(s)
	case string:
		*e = BillingPeriodType(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingPeriodType: %T", src)
	}
	return nil
}

type NullBillingPeriodType struct {
	BillingPeriodType BillingPeriodType `json:"billing_period_type"`
	Valid             bool              `json:"valid"` // Valid is true if BillingPeriodType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingPeriodType) Scan(value interface{}) error {
	if value == nil {
		ns.BillingPeriodType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingPeriodType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingPeriodType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingPeriodType), nil
}

type InvoiceStatus string

const (
	InvoiceStatusDraft  InvoiceStatus = "draft"
	InvoiceStatusIssued InvoiceStatus = "issued"
	InvoiceStatusPaid   InvoiceStatus = "paid"
	InvoiceStatusVoid   InvoiceStatus = "void"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type OperatingStatus string

const (
	OperatingStatusActive      OperatingStatus = "active"
	OperatingStatusInactive    OperatingStatus = "inactive"
	OperatingStatusMaintenance OperatingStatus = "maintenance"
	OperatingStatusDeprecated  OperatingStatus = "deprecated"
)

func (e *OperatingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OperatingStatus(s)
	case string:
		*e = OperatingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OperatingStatus: %T", src)
	}
	return nil
}

type NullOperatingStatus struct {
	OperatingStatus OperatingStatus `json:"operating_status"`
	Valid           bool            `json:"valid"` // Valid is true if OperatingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOperatingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OperatingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OperatingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOperatingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OperatingStatus), nil
}

type PricingType string

const (
	PricingTypeFlat    PricingType = "flat"
	PricingTypeTiered  PricingType = "tiered"
	PricingTypePerUnit PricingType = "per_unit"
)

func (e *PricingType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PricingType(s)
	case string:
		*e = PricingType(s)
	default:
		return fmt.Errorf("unsupported scan type for PricingType: %T", src)
	}
	return nil
}

type NullPricingType struct {
	PricingType PricingType `json:"pricing_type"`
	Valid       bool        `json:"valid"` // Valid is true if PricingType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPricingType) Scan(value interface{}) error {
	if value == nil {
		ns.PricingType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PricingType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPricingType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PricingType), nil
}

type Customer struct {
	ID          pgtype.UUID        `json:"id"`
	OperatorID  pgtype.UUID        `json:"operator_id"`
	ExternalID  pgtype.UUID        `json:"external_id"`
	Name        string             `json:"name"`
	Email       string             `json:"email"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	PlanName    string             `json:"plan_name"`
}

type Invoice struct {
	ID          pgtype.UUID        `json:"id"`
	OperatorID  pgtype.UUID        `json:"operator_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	AmountCents int64              `json:"amount_cents"`
	Status      InvoiceStatus      `json:"status"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	LineItems   []byte             `json:"line_items"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Operator struct {
	ID            pgtype.UUID        `json:"id"`
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	LogoUrl       pgtype.Text        `json:"logo_url"`
	ApiKeyHash    string             `json:"api_key_hash"`
	WebhookSecret string             `json:"webhook_secret"`
	SupportEmail  pgtype.Text        `json:"support_email"`
	WebsiteUrl    pgtype.Text        `json:"website_url"`
	Status        OperatingStatus    `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	PasswordHash  pgtype.Text        `json:"password_hash"`
}

type Plan struct {
	ID            pgtype.UUID        `json:"id"`
	PricingModel  PricingType        `json:"pricing_model"`
	UnitPriceCent pgtype.Int8        `json:"unit_price_cent"`
	Tiers         []byte             `json:"tiers"`
	BillingPeriod BillingPeriodType  `json:"billing_period"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Name          string             `json:"name"`
	OperatorID    pgtype.UUID        `json:"operator_id"`
}

type UsageAggregate struct {
	ID          pgtype.UUID        `json:"id"`
	OperatorID  pgtype.UUID        `json:"operator_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	EventName   string             `json:"event_name"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	TotalUnits  int64              `json:"total_units"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UsageEvent struct {
	ID             pgtype.UUID        `json:"id"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	OperatorID     pgtype.UUID        `json:"operator_id"`
	EventName      string             `json:"event_name"`
	Quantity       int64              `json:"quantity"`
	IdempotencyKey string             `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type WebhookDelivery struct {
	ID            pgtype.UUID        `json:"id"`
	EndpointID    pgtype.UUID        `json:"endpoint_id"`
	EventType     string             `json:"event_type"`
	Payload       []byte             `json:"payload"`
	ResponseCode  pgtype.Int4        `json:"response_code"`
	ResponseBody  pgtype.Text        `json:"response_body"`
	AttemptNumber int32              `json:"attempt_number"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type WebhookEndpoint struct {
	ID            pgtype.UUID        `json:"id"`
	OperatorID    pgtype.UUID        `json:"operator_id"`
	Url           string             `json:"url"`
	SigningSecret string             `json:"signing_secret"`
	Events        []string           `json:"events"`
	Active        bool               `json:"active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}
