// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: operators.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOperator = `-- name: CreateOperator :one
INSERT INTO operators 
(name, description, status, api_key_hash, webhook_secret, support_email, website_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, description, logo_url, api_key_hash, webhook_secret, support_email, website_url, status, created_at, updated_at
`

type CreateOperatorParams struct {
	Name          string             `json:"name"`
	Description   pgtype.Text        `json:"description"`
	Status        OperatingStatus    `json:"status"`
	ApiKeyHash    string             `json:"api_key_hash"`
	WebhookSecret string             `json:"webhook_secret"`
	SupportEmail  pgtype.Text        `json:"support_email"`
	WebsiteUrl    pgtype.Text        `json:"website_url"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) (Operator, error) {
	row := q.db.QueryRow(ctx, createOperator,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ApiKeyHash,
		arg.WebhookSecret,
		arg.SupportEmail,
		arg.WebsiteUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.ApiKeyHash,
		&i.WebhookSecret,
		&i.SupportEmail,
		&i.WebsiteUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperator = `-- name: GetOperator :one
SELECT id, name, description, logo_url, api_key_hash, webhook_secret, support_email, website_url, status, created_at, updated_at FROM operators WHERE id = $1
`

func (q *Queries) GetOperator(ctx context.Context, id pgtype.UUID) (Operator, error) {
	row := q.db.QueryRow(ctx, getOperator, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.ApiKeyHash,
		&i.WebhookSecret,
		&i.SupportEmail,
		&i.WebsiteUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
