// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlan = `-- name: CreatePlan :one
INSERT INTO plans 
(operator_id,name,pricing_model, unit_price_cent,tiers, billing_period) 
VALUES ($1,$2,$3,$4,$5,$6) 
RETURNING id, pricing_model, unit_price_cent, tiers, billing_period, created_at, updated_at, name, operator_id
`

type CreatePlanParams struct {
	OperatorID    pgtype.UUID       `json:"operator_id"`
	Name          string            `json:"name"`
	PricingModel  PricingType       `json:"pricing_model"`
	UnitPriceCent pgtype.Int8       `json:"unit_price_cent"`
	Tiers         []byte            `json:"tiers"`
	BillingPeriod BillingPeriodType `json:"billing_period"`
}

func (q *Queries) CreatePlan(ctx context.Context, arg CreatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, createPlan,
		arg.OperatorID,
		arg.Name,
		arg.PricingModel,
		arg.UnitPriceCent,
		arg.Tiers,
		arg.BillingPeriod,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PricingModel,
		&i.UnitPriceCent,
		&i.Tiers,
		&i.BillingPeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OperatorID,
	)
	return i, err
}

const deletePlan = `-- name: DeletePlan :exec
DELETE FROM plans WHERE id = $1
`

func (q *Queries) DeletePlan(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePlan, id)
	return err
}

const getPlan = `-- name: GetPlan :one
SELECT id, pricing_model, unit_price_cent, tiers, billing_period, created_at, updated_at, name, operator_id FROM plans WHERE id = $1
`

func (q *Queries) GetPlan(ctx context.Context, id pgtype.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PricingModel,
		&i.UnitPriceCent,
		&i.Tiers,
		&i.BillingPeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OperatorID,
	)
	return i, err
}

const getPlanByName = `-- name: GetPlanByName :one
SELECT id, pricing_model, unit_price_cent, tiers, billing_period, created_at, updated_at, name, operator_id FROM plans WHERE operator_id = $1 AND name = $2
`

type GetPlanByNameParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	Name       string      `json:"name"`
}

func (q *Queries) GetPlanByName(ctx context.Context, arg GetPlanByNameParams) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlanByName, arg.OperatorID, arg.Name)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PricingModel,
		&i.UnitPriceCent,
		&i.Tiers,
		&i.BillingPeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OperatorID,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT id, pricing_model, unit_price_cent, tiers, billing_period, created_at, updated_at, name, operator_id FROM plans WHERE operator_id = $1
`

func (q *Queries) ListPlans(ctx context.Context, operatorID pgtype.UUID) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans, operatorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.PricingModel,
			&i.UnitPriceCent,
			&i.Tiers,
			&i.BillingPeriod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.OperatorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans SET 
    name = COALESCE($1, name),
    pricing_model = COALESCE($2, pricing_model),
    unit_price_cent = COALESCE($3, unit_price_cent),
    tiers = COALESCE($4, tiers),
    billing_period = COALESCE($5, billing_period),
    updated_at = NOW()
WHERE id = $6 RETURNING id, pricing_model, unit_price_cent, tiers, billing_period, created_at, updated_at, name, operator_id
`

type UpdatePlanParams struct {
	Name          string            `json:"name"`
	PricingModel  PricingType       `json:"pricing_model"`
	UnitPriceCent pgtype.Int8       `json:"unit_price_cent"`
	Tiers         []byte            `json:"tiers"`
	BillingPeriod BillingPeriodType `json:"billing_period"`
	ID            pgtype.UUID       `json:"id"`
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Name,
		arg.PricingModel,
		arg.UnitPriceCent,
		arg.Tiers,
		arg.BillingPeriod,
		arg.ID,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.PricingModel,
		&i.UnitPriceCent,
		&i.Tiers,
		&i.BillingPeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.OperatorID,
	)
	return i, err
}
