// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usageAggregates.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const upsertUsageAggregate = `-- name: UpsertUsageAggregate :exec
INSERT INTO usage_aggregates
(operator_id,customer_id,event_name,period_start,period_end,total_units)
VALUES ($1,$2,$3,$4,$5,$6)
ON CONFLICT (customer_id,event_name,period_start) DO UPDATE SET total_units = usage_aggregates.total_units + EXCLUDED.total_units, updated_at = NOW()
`

type UpsertUsageAggregateParams struct {
	OperatorID  pgtype.UUID        `json:"operator_id"`
	CustomerID  pgtype.UUID        `json:"customer_id"`
	EventName   string             `json:"event_name"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	TotalUnits  int64              `json:"total_units"`
}

func (q *Queries) UpsertUsageAggregate(ctx context.Context, arg UpsertUsageAggregateParams) error {
	_, err := q.db.Exec(ctx, upsertUsageAggregate,
		arg.OperatorID,
		arg.CustomerID,
		arg.EventName,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.TotalUnits,
	)
	return err
}
