// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO webhook_deliveries (endpoint_id,event_type,payload)
VALUES ($1,$2,$3)
RETURNING id, endpoint_id, event_type, payload, response_code, response_body, attempt_number, delivered_at, created_at, status
`

type CreateDeliveryAttemptParams struct {
	EndpointID pgtype.UUID `json:"endpoint_id"`
	EventType  string      `json:"event_type"`
	Payload    []byte      `json:"payload"`
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createDeliveryAttempt, arg.EndpointID, arg.EventType, arg.Payload)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.AttemptNumber,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}

const getActiveWebhooksByOperatorID = `-- name: GetActiveWebhooksByOperatorID :one
SELECT id, operator_id, url, signing_secret, events, active, created_at FROM webhook_endpoints WHERE operator_id = $1 AND active = true
`

func (q *Queries) GetActiveWebhooksByOperatorID(ctx context.Context, operatorID pgtype.UUID) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getActiveWebhooksByOperatorID, operatorID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Url,
		&i.SigningSecret,
		&i.Events,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const updateDeliveryResult = `-- name: UpdateDeliveryResult :one
UPDATE webhook_deliveries 
SET response_code = $1,
response_body = $2,
status = $3,
delivered_at = NOW(),
attempt_number = attempt_number + 1
WHERE id = $4
RETURNING id, endpoint_id, event_type, payload, response_code, response_body, attempt_number, delivered_at, created_at, status
`

type UpdateDeliveryResultParams struct {
	ResponseCode pgtype.Int4 `json:"response_code"`
	ResponseBody pgtype.Text `json:"response_body"`
	Status       string      `json:"status"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateDeliveryResult(ctx context.Context, arg UpdateDeliveryResultParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, updateDeliveryResult,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.Status,
		arg.ID,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.AttemptNumber,
		&i.DeliveredAt,
		&i.CreatedAt,
		&i.Status,
	)
	return i, err
}
